### ISSUE TITLE
作者你好，现在API还能用吗？

### ISSUE THREAD

**Issue by QYPerson** [wsb200514/34miao_API#1]

**Comment by wsb200514** [comment]
不好意思，前两天服务器刚到期，没有续费，所以不能用了。抱歉。

**Comment by QYPerson** [comment]
好可惜，那么好的一个网站，作者，你有简书之类的技术博客吗？我也想做一个抓取别人应用的程序，不知道如何下手。

**Comment by wsb200514** [comment]
1、服务器续了费，API暂时可用，但未来不确定，随时可能会被关闭，请知悉。
2、我用的是scrapy做数据抓取，你可以看看这方面的材料。
